### ISSUE TITLE
Error In Workflow org.jeef.alfred.ecobee

### ISSUE THREAD

**Issue by adammiros** [jeeftor/alfredEcobee#1]
So apparently is says that it cant "concatenate str" and "NoneType Objects". I'm still a novice to python so I understand the first half it tries to convert to a string and fails and the other I have no clue. I will try to take a look at it later, but still the Nonetype objects seems to cause a major crash.

<img width="581" alt="screen shot 2017-05-22 at 9 42 35 pm" src="https://cloud.githubusercontent.com/assets/3486942/26335099/b1231a70-3f37-11e7-8235-5693f358a782.png">

**Comment by dan6b** [comment]
Same error here as well. FYI, I have two ecobee thermostats.

**Comment by jeeftor** [comment]
:( I'll try to check tomorrow. I should have some free time

**Comment by dan6b** [comment]
Cool. Thanks!


On June 21, 2017 at 4:00:12 PM, Jeef (notifications@github.com) wrote:

:( I'll try to check tomorrow. I should have some free time

**Comment by jeeftor** [comment]
Hey can you guys run `edbg` (workflow debug command) and open the `workflow:openlog` option.  and paste in the text and i'll take a look!  My version is currently working nicely so we should be able to figure something out

**Comment by dan6b** [comment]
Hi,

Please see below, and thanks for looking into it:

12:47:13 workflow.py:2207 ERROR    cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/workflow/workflow.py", line 2200, in run
    func(self)
  File "get_temps.py", line 20, in main
    tdata = e.get_thermostats()
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 107, in get_thermostats
    return self.wf.cached_data('getThermostats', get_data, max_age=1)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/workflow/workflow.py", line 1833, in cached_data
    data = data_func()
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 103, in get_data
    response = self.get_with_params(url, querystring)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 52, in get_with_params
    response = requests.request("GET", url, headers=self.get_headers(), params=params)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 23, in get_headers
    return {'authorization': 'Bearer ' + self.access_token,
TypeError: cannot concatenate 'str' and 'NoneType' objects
12:47:25 workflow.py:2207 ERROR    cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/workflow/workflow.py", line 2200, in run
    func(self)
  File "get_temps.py", line 20, in main
    tdata = e.get_thermostats()
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 107, in get_thermostats
    return self.wf.cached_data('getThermostats', get_data, max_age=1)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/workflow/workflow.py", line 1833, in cached_data
    data = data_func()
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 103, in get_data
    response = self.get_with_params(url, querystring)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 52, in get_with_params
    response = requests.request("GET", url, headers=self.get_headers(), params=params)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 23, in get_headers
    return {'authorization': 'Bearer ' + self.access_token,
TypeError: cannot concatenate 'str' and 'NoneType' objects
12:49:26 workflow.py:2469 INFO     Checking for update ...
12:49:34 workflow.py:2469 INFO     Checking for update ...
12:49:34 background.py:172 INFO     Task `__workflow_update_check` is already running
15:47:39 workflow.py:2207 ERROR    cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/workflow/workflow.py", line 2200, in run
    func(self)
  File "get_temps.py", line 20, in main
    tdata = e.get_thermostats()
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 107, in get_thermostats
    return self.wf.cached_data('getThermostats', get_data, max_age=1)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/workflow/workflow.py", line 1833, in cached_data
    data = data_func()
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 103, in get_data
    response = self.get_with_params(url, querystring)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 52, in get_with_params
    response = requests.request("GET", url, headers=self.get_headers(), params=params)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 23, in get_headers
    return {'authorization': 'Bearer ' + self.access_token,
TypeError: cannot concatenate 'str' and 'NoneType' objects
15:50:08 workflow.py:2207 ERROR    cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/workflow/workflow.py", line 2200, in run
    func(self)
  File "get_temps.py", line 20, in main
    tdata = e.get_thermostats()
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 107, in get_thermostats
    return self.wf.cached_data('getThermostats', get_data, max_age=1)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/workflow/workflow.py", line 1833, in cached_data
    data = data_func()
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 103, in get_data
    response = self.get_with_params(url, querystring)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 52, in get_with_params
    response = requests.request("GET", url, headers=self.get_headers(), params=params)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 23, in get_headers
    return {'authorization': 'Bearer ' + self.access_token,
TypeError: cannot concatenate 'str' and 'NoneType' objects
19:38:41 workflow.py:2207 ERROR    cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/workflow/workflow.py", line 2200, in run
    func(self)
  File "get_temps.py", line 20, in main
    tdata = e.get_thermostats()
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 107, in get_thermostats
    return self.wf.cached_data('getThermostats', get_data, max_age=1)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/workflow/workflow.py", line 1833, in cached_data
    data = data_func()
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 103, in get_data
    response = self.get_with_params(url, querystring)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 52, in get_with_params
    response = requests.request("GET", url, headers=self.get_headers(), params=params)
  File "/Users/dada/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0ABF340A-FC73-4554-A3E7-762A2BED8B70/src/ecobee/__init__.py", line 23, in get_headers
    return {'authorization': 'Bearer ' + self.access_token,
TypeError: cannot concatenate 'str' and 'NoneType' objects
19:39:01 workflow.py:2469 INFO     Checking for update ...
19:39:06 workflow.py:2469 INFO     Checking for update ...
19:39:06 background.py:172 INFO     Task `__workflow_update_check` is already running



On June 22, 2017 at 5:35:33 PM, Jeef (notifications@github.com) wrote:

Hey can you guys run edbg and open the workflow:openlog option. and paste in the text and i'll take a look! My version is currently working nicely so we should be able to figure something out

**Comment by jeeftor** [comment]
So looks like the issue is that `self.access_token` is unset (aka `None`) and so I cant print out the string below:

` return {'authorization': 'Bearer ' + self.access_token,`

Which leads to the question - do you not have an access token?  Did you do the authorization stuff as specified in the README ?  

I can protect this line - but I'm not sure it will do much if the auth hasn't happened yet.

**Comment by jeeftor** [comment]
So here is how things work.  Ecobee has a whole token setup to access their stuff.  So once you've got your authorization and tokens setup correctly they will be stored to a cache

The lines:

```python
self.api_key = self.wf.stored_data('APP_KEY')
self.access_token = self.wf.stored_data('ACCESS_TOKEN')
self.refresh_token = self.wf.stored_data('REFRESH_TOKEN')      
```
are retrieving the tokens form the cache and using them to access ecobee.  The issue is I guess in your case there are no tokens so these values don't get set and KABOOMZA.  

Can you verify you've run the auth process and if so we have a deeper issue.  `ea` will probably fire up that little window for you.

**Comment by adammiros** [comment]
Ok so I just got the email that this thread is alive (hurray!) Anyway, I managed to look into it a bit and  I did as you suggested by rerunning the authorization problem, however the problem still persisted. I followed this by reinstalling the plugin all together and I still have the same issue. Hopefully the log I attached below can help.


https://pastebin.com/3MGYZSAv


I will still try to look into this but I'm not sure what the issue is.

**Comment by dan6b** [comment]
I did authenticate before getting the error.

Today I’ve removed the workflow from Alfred, and the app from ecobee’s web portal. I’ve then restarted Alfred, reinstalled the workflow, ran eauth, enter the code, but I still get the same error. 

So I’ve ran edbg workflow:remove settings and remove cache.

I’ve then ran again the eauth, removed and added again the app on ecobee’s portal, and for the FIRST TIME I got a notification message that the authentication was successful. Ran etemp and it worked!

Thanks for all the help and for the nice extension!




On June 23, 2017 at 5:58:23 AM, Jeef (notifications@github.com) wrote:

So looks like the issue is that self.access_token is unset (aka None) and so I cant print out the string below:

return {'authorization': 'Bearer ' + self.access_token,

Which leads to the question - do you not have an access token? Did you do the authorization stuff as specified in the README ?

I can protect this line - but I'm not sure it will do much if the auth hasn't happened yet.

**Comment by jeeftor** [comment]
OK good news!  I deleted and re-installed and i didn't get the error - then i removed all the cache and settings and data files and i did get the error - so I should be able to fix it :)

**Comment by jeeftor** [comment]
So i made a new release - may not fix things but has a ton of logging.  I was able to get a new auth token and re-setup the plugin by doing a clean install with this version.  

Here is what my logs look like when it works:

> 
> 15:29:27 authorize.py:29 INFO     Auth Pin: sb9z
> 15:29:27 authorize.py:30 INFO     AUTH_CODE: I9qzdIgYv4TKxfp2DWvEt3dVzviHH54p
> 15:29:27 authorize.py:43 INFO     Starting Background Task
> 15:29:27 bg_check_auth.py:59 INFO     BG Auth Check Started
> 15:29:27 bg_check_auth.py:10 INFO     AUTH_CODE: I9qzdIgYv4TKxfp2DWvEt3dVzviHH54p
> 15:29:27 bg_check_auth.py:11 INFO     APP_KEY:   CC1mvejObvFwoAqPn8VfVe7OfTFaPDEp
> 15:29:27 bg_check_auth.py:22 INFO     Starting Loop
> 15:29:32 bg_check_auth.py:27 INFO     Elapsed time 0
> 15:29:33 bg_check_auth.py:37 INFO     https://api.ecobee.com/token
> 15:29:33 bg_check_auth.py:38 INFO     {'code': u'I9qzdIgYv4TKxfp2DWvEt3dVzviHH54p', 'client_id': u'CC1mvejObvFwoAqPn8VfVe7OfTFaPDEp', 'grant_type': 'ecobeePin'}
> 15:29:33 bg_check_auth.py:39 INFO     401
> 15:29:38 bg_check_auth.py:27 INFO     Elapsed time 5
> 15:29:38 bg_check_auth.py:37 INFO     https://api.ecobee.com/token
> 15:29:38 bg_check_auth.py:38 INFO     {'code': u'I9qzdIgYv4TKxfp2DWvEt3dVzviHH54p', 'client_id': u'CC1mvejObvFwoAqPn8VfVe7OfTFaPDEp', 'grant_type': 'ecobeePin'}
> 15:29:38 bg_check_auth.py:39 INFO     401
> 15:29:43 bg_check_auth.py:27 INFO     Elapsed time 10
> 15:29:43 bg_check_auth.py:37 INFO     https://api.ecobee.com/token
> 15:29:43 bg_check_auth.py:38 INFO     {'code': u'I9qzdIgYv4TKxfp2DWvEt3dVzviHH54p', 'client_id': u'CC1mvejObvFwoAqPn8VfVe7OfTFaPDEp', 'grant_type': 'ecobeePin'}
> 15:29:43 bg_check_auth.py:39 INFO     401
> 15:29:48 bg_check_auth.py:27 INFO     Elapsed time 15
> 15:29:48 bg_check_auth.py:37 INFO     https://api.ecobee.com/token
> 15:29:48 bg_check_auth.py:38 INFO     {'code': u'I9qzdIgYv4TKxfp2DWvEt3dVzviHH54p', 'client_id': u'CC1mvejObvFwoAqPn8VfVe7OfTFaPDEp', 'grant_type': 'ecobeePin'}
> 15:29:48 bg_check_auth.py:39 INFO     401
> 15:29:53 bg_check_auth.py:27 INFO     Elapsed time 20
> 15:29:54 bg_check_auth.py:37 INFO     https://api.ecobee.com/token
> 15:29:54 bg_check_auth.py:38 INFO     {'code': u'I9qzdIgYv4TKxfp2DWvEt3dVzviHH54p', 'client_id': u'CC1mvejObvFwoAqPn8VfVe7OfTFaPDEp', 'grant_type': 'ecobeePin'}
> 15:29:54 bg_check_auth.py:39 INFO     401
> 15:29:59 bg_check_auth.py:27 INFO     Elapsed time 26
> 15:29:59 bg_check_auth.py:37 INFO     https://api.ecobee.com/token
> 15:29:59 bg_check_auth.py:38 INFO     {'code': u'I9qzdIgYv4TKxfp2DWvEt3dVzviHH54p', 'client_id': u'CC1mvejObvFwoAqPn8VfVe7OfTFaPDEp', 'grant_type': 'ecobeePin'}
> 15:29:59 bg_check_auth.py:39 INFO     401
> 15:30:04 bg_check_auth.py:27 INFO     Elapsed time 31
> 15:30:04 bg_check_auth.py:37 INFO     https://api.ecobee.com/token
> 15:30:04 bg_check_auth.py:38 INFO     {'code': u'I9qzdIgYv4TKxfp2DWvEt3dVzviHH54p', 'client_id': u'CC1mvejObvFwoAqPn8VfVe7OfTFaPDEp', 'grant_type': 'ecobeePin'}
> 15:30:04 bg_check_auth.py:39 INFO     200
> 15:30:04 bg_check_auth.py:43 INFO     Auth success
> 15:30:04 bg_check_auth.py:54 INFO     Terminating background process

**Comment by jeeftor** [comment]
(the release is a GitHub release - not Packal or anything like that FYI)

**Comment by jeeftor** [comment]
Guys -  you still working on this?

**Comment by adammiros** [comment]
Sorry for the delay. I just managed to test it and it works fine now! With the newest update you dont have to copy type in the code on the ecobee site but just click on the copy code and go to ecobee site. Doing that will work because if you just type in the given code it does not fully authorize. So in short, the newest update fixes it.
